### ISSUE TITLE
REDCap form changes - multiple test methods

### ISSUE THREAD

**Issue by roseanna-hamilton** [gosh-dre/gmsa_genomic_fhir_webapp#52]
Some reports use multiple test methods, I have duplicated the test method type field three times in the Test Method form to account for this in REDCap

**Comment by stefpiatek** [comment]
Applying this using formik might be quite fun, Ideally we'd have a drop down where you could select multiple variants. The FHIR API allows for multiple test reasons so that should be relatively straightforward. I think to keep consistency we may need to process these as separate entities, as the reason for test is part of the primary key. So if we had two reasons for tests, the bundle would contain 2x each of the bundle resources, one for each reason for test
